name: Joel Sabillon - Front-End Developer
description: Personal Website

url: "http://localhost:4000"

paginate: 15
paginate_path: blog/page:num

markdown: rdiscount
permalink: /blog/:title
highlighter: rouge